//admin types
export const ADMIN_LOGIN_START = "ADMIN_LOGIN_START"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADD_DOCTOR_START = "ADD_DOCTOR_START";
export const ADD_DOCTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_DOCTOR_FAIL = "ADD_DOCTOR_FAIL";
export const GET_ALL_DOCTOR_START = "GET_ALL_DOCTOR_START";
export const GET_ALL_DOCTOR_SUCCESS = "GET_ALL_DOCTOR_SUCCESS";
export const GET_ALL_DOCTOR_FAIL = "GET_ALL_DOCTOR_FAIL";
export const CHANGE_AVAILABILITY_SUCCESS = "CHANGE_AVAILABILITY_SUCCESS";
export const GET_ALL_APPOINTMENTS_START = "GET_ALL_APPOINTMENTS_START";
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS";
export const GET_ALL_APPOINTMENTS_FAIL = "GET_ALL_APPOINTMENTS_FAIL";
export const CHANGE_APPOINTMENT_STATUS_SUCCESS = "CHANGE_APPOINTMENT_STATUS_SUCCESS";
export const GET_STATISTICS_START = "GET_STATISTICS_START";
export const GET_STATISTICS_SUCCESS = "GET_STATISTICS_SUCCESS";
export const GET_STATISTICS_FAIL = "GET_STATISTICS_FAIL";
export const GET_DOCTOR_BY_ID_START = "GET_DOCTOR_BY_ID_START";
export const GET_DOCTOR_BY_ID_SUCCESS = "GET_DOCTOR_BY_ID_SUCCESS";
export const GET_DOCTOR_BY_ID_FAIL = "GET_DOCTOR_BY_ID_FAIL";
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const GET_PROFILE_START = "GET_PROFILE_START"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"
export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const BOOK_APPOINTEMNT_START = "BOOK_APPOINTEMNT_START"
export const BOOK_APPOINTEMNT_SUCCESS = "BOOK_APPOINTEMNT_SUCCESS"
export const BOOK_APPOINTEMNT_FAIL = "BOOK_APPOINTEMNT_FAIL"
export const GET_MY_APPOINTEMNT_START = "GET_MY_APPOINTEMNT_START"
export const GET_MY_APPOINTEMNT_SUCCESS = "GET_MY_APPOINTEMNT_SUCCESS"
export const GET_MY_APPOINTEMNT_FAIL = "GET_MY_APPOINTEMNT_FAIL"
export const CANCEL_APPOINTEMNT_START = "CANCEL_APPOINTEMNT_START"
export const CANCEL_APPOINTEMNT_SUCCESS = "CANCEL_APPOINTEMNT_SUCCESS"
export const CANCEL_APPOINTEMNT_FAIL = "CANCEL_APPOINTEMNT_FAIL"

// review types
export const GET_REVIEWS_START = "GET_REVIEWS_START"
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS"
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL"
export const ADD_REVIEW_START = "ADD_REVIEW_START"
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL"

// blog types
export const GET_ALL_BLOGS_START = "GET_ALL_BLOGS_START"
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS"
export const GET_ALL_BLOGS_FAIL = "GET_ALL_BLOGS_FAIL"
export const ADD_BLOG_START = "ADD_BLOG_START"
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS"
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL"
export const REMOVE_BLOG_SUCCESS = "REMOVE_BLOG_SUCCESS"

// doctor auth types
export const DOCTOR_LOGIN_START = "DOCTOR_LOGIN_START"
export const DOCTOR_LOGIN_SUCCESS = "DOCTOR_LOGIN_SUCCESS"
export const DOCTOR_LOGIN_FAIL = "DOCTOR_LOGIN_FAIL"
export const DOCTOR_LOGOUT_SUCCESS = "DOCTOR_LOGOUT_SUCCESS"

// doctor appointments
export const GET_DOCTOR_APPOINTMENTS_START = "GET_DOCTOR_APPOINTMENTS_START"
export const GET_DOCTOR_APPOINTMENTS_SUCCESS = "GET_DOCTOR_APPOINTMENTS_SUCCESS"
export const GET_DOCTOR_APPOINTMENTS_FAIL = "GET_DOCTOR_APPOINTMENTS_FAIL"
export const CHANGE_DOCTOR_APPOINTMENT_STATUS_SUCCESS = "CHANGE_DOCTOR_APPOINTMENT_STATUS_SUCCESS"